#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

service="$1"
service_path="$PLUSHU_SERVICES_DIR/$service"
target_dir="$2"
cidfile="$target_dir/docker/run.cid"

# kill the service if it appears to be running
if [[ -f "$cidfile" ]]; then
  # TODO: script to perform shutdown operations?
  "$PLUSHU_ROOT/lib/plushook" docker-rm-cidfile "$cidfile"
fi
